### ISSUE TITLE
[Suggestion] More config options?

### ISSUE THREAD

**Issue by MasterEnderman** [cleverpanda/PrimitiveTools#2]
I would like to suggest more config options, because i want to use your mod in one of my packs.

- Disable Flint Drop from Sand
- Disable Flint Drop from Gravel
- Disable Vine Drop when using a knife

Thank you for making this awesome mod. Keep up the good work!

**Comment by MasterEnderman** [comment]
As you suggested i changed the configs to "-1": https://pastebin.com/QUgjGiPS

but now every sand / gravel i break drops flint
this also happens to the vines if i break them with a knife

**Comment by Exsolutus** [comment]
After doing some testing, I have found all config values less than 1 become 1, and all config values greater than 100 become 100. This explains why "-1" did not work.

Config options to disable each drop change in this mod individually would be greatly appreciated!
